name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    
    steps:
      - name: test
        run: hostname
        
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        
        env:
          sshPrivateKey: ${{ secrets.AWS_KEY }}
          remoteHost: ${{ secrets.HOST_DNS }}
          remoteUser: ${{ secrets.AWS_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
