name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    
    steps:
      - name: test
        run: echo hostname1
        
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.AWS_KEY}}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.HOST_DNS}}
          REMOTE_USER: ${{secrets.AWS_USERNAME}}
          TARGET: ${{secrets.TARGET_DIR}}
          
